fix(cpu-template-helper): Don't show error message twice
The CPU template helper tool showed its error message twice as follows:
```
$cpu-template-helper fingerprint compare --prev A.json --curr B.json
Difference detected between source and target:\\n{
  "name": "kernel_version",
  "prev": "5.10.215-203.850.amzn2.x86_64",
  "curr": "6.1.84-99.169.amzn2023.x86_64"
}
Error: FingerprintCompare(DiffDetected("{\n  \"name\": \"kernel_..."))
```

It is because it returned `Result` from `main()` to return an exit code
and it shows its error message on error. Instead just return the exit
code using `std::process::exit()`.

Signed-off-by: Takahiro Itazuri <itazur@amazon.com>