ci(gh_release.py): validate version parameter
The version parameter is vulnerable to command injection. I.e.

    gh_release.py --version '**v1.2.4;id #**'

Validate the version parameter so it's not accepted.

    error: argument --version: invalid version value: '**v1.2.4;id #**'

Signed-off-by: Pablo Barbáchano <pablob@amazon.com>