fix(test): add sleep to wait for socat spinup in test_tap_offload
We are seeing an intermittent failure of the form

FAILED test_net.py::test_tap_offload - ChildProcessError:
[17861] Command:['ssh', ..., 'sync; cat /tmp/out.txt']
[17861] stdout:
[17861] stderr:
cat: /tmp/out.txt: No such file or directory

It seems this is due to not waiting long enough for socat to spin up, so
add a quick sleep which makes the issue disappear.

Signed-off-by: Patrick Roy <roypat@amazon.co.uk>