fix: restore the id parameter default
Running Firecracker without parameters causes a panic.

```
[anonymous-instance:main] Running Firecracker v1.5.0-dev
[anonymous-instance:main] Firecracker panicked at 'called
`Option::unwrap()` on a `None` value',
src/firecracker/src/main.rs:291:52
[1] 980007 IOT instruction
./firecracker
```

Fixes: 332f2184ae29265fbae1648469e073fc7f987378

Signed-off-by: Pablo Barbáchano <pablob@amazon.com>