pretty print panics
Instead of printing the PanicInfo using debug, we can use display
as this generates a human readable panic.

Before:
Panic occurred: PanicInfo { payload: Any, message: Some(Failed to
open the API socket: IO Error: Io(Os ...

After:
Firecracker panicked at 'Failed to open the API socket: IO Error:
...

This is the first step in having human readable panics. Next we
should implement Display for errors that can generate panics.

Signed-off-by: Andreea Florescu <fandree@amazon.com>