fix(test): retry reading pid file a few times
Sometimes, tests intermittently fail with

FileNotFoundError: [Errno 2] No such file or directory:
'/[snip]/root/firecracker.pid'

or

ValueError: invalid literal for int() with base 10: ''
framework/microvm.py:485: in firecracker_pid
    return int(self.jailer.pid_file.read_text(encoding="ascii"))

It seems this is because we check the pid file too early (especially
when creating the memory monitor), so give it a few retries.

Signed-off-by: Patrick Roy <roypat@amazon.co.uk>