chore: surface error vstate unit test
Otherwise the reason is not very helpful:

panicked at 'assertion failed: vcpu.restore_state(&state).is_ok()'

Signed-off-by: Pablo Barbáchano <pablob@amazon.com>